name: Question
description: Ask a question about the project
title: '[Question] '
labels: ['question']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! We'll do our best to help.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Your question here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your question
      placeholder: What are you trying to accomplish?

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does your question fall into?
      options:
        - Setup/Installation
        - Usage/How-to
        - Architecture
        - Quality Gates
        - CI/CD
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What I've Tried
      description: Describe what you've already tried or researched
      placeholder: I've tried... I've read...

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have read the documentation
          required: true
        - label: I have checked the troubleshooting guide
          required: false
